In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('Bondora_raw.csv')

C:\Users\nikhi\AppData\Local\Temp\ipykernel_6920\3173852280.py:1: DtypeWarning: Columns (34,37,38,80,82,83,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Bondora_raw.csv')

In [6]:
# Load the CSV file with low_memory=False
data = pd.read_csv('Bondora_raw.csv', low_memory=False)

# Display the first few rows
print(data.head())

  ReportAsOfEOD                                LoanId  LoanNumber  \
0    2020-01-27  F0660C80-83F3-4A97-8DA0-9C250112D6EC         659
1    2020-01-27  978BB85B-1C69-4D51-8447-9C240104A3A2         654
2    2020-01-27  EA44027E-7FA7-4BB2-846D-9C1F013C8A22         641
3    2020-01-27  CE67AD25-2951-4BEE-96BD-9C2700C61EF4         668
4    2020-01-27  9408BF8C-B159-4D6A-9D61-9C2400A986E3         652

           ListedOnUTC     BiddingStartedOn  BidsPortfolioManager  BidsApi  \
0  2009-06-11 16:40:39  2009-06-11 16:40:39                     0        0
1  2009-06-10 15:48:57  2009-06-10 15:48:57                     0        0
2  2009-06-05 19:12:29  2009-06-05 19:12:29                     0        0
3  2009-06-13 12:01:20  2009-06-13 12:01:20                     0        0
4  2009-06-10 10:17:13  2009-06-10 10:17:13                     0        0

   BidsManual  UserName  NewCreditCustomer  ...  \
0    115.0410      KARU               True  ...
1    140.6057  koort681              False  ...
2    319.5580       0ie               True  ...
3     57.5205    Alyona               True  ...
4    319.5582       Kai               True  ...

  PreviousEarlyRepaymentsCountBeforeLoan GracePeriodStart GracePeriodEnd  \
0                                      0              NaN            NaN
1                                      0              NaN            NaN
2                                      0              NaN            NaN
3                                      0              NaN            NaN
4                                      0              NaN            NaN

  NextPaymentDate NextPaymentNr NrOfScheduledPayments  ReScheduledOn  \
0             NaN           NaN                   NaN            NaN
1             NaN           NaN                   NaN            NaN
2             NaN           NaN                   NaN            NaN
3             NaN           NaN                   NaN            NaN
4             NaN           NaN                   NaN            NaN

   PrincipalDebtServicingCost  InterestAndPenaltyDebtServicingCost  \
0                         0.0                                  0.0
1                         0.0                                  0.0
2                         0.0                                  0.0
3                         0.0                                  0.0
4                         0.0                                  0.0

   ActiveLateLastPaymentCategory
0                            NaN
1                            NaN
2                           180+
3                            NaN
4                           180+

[5 rows x 112 columns]

In [7]:

# Separate numeric and categorical columns
numeric_columns = data.select_dtypes(include=['number']).columns
categorical_columns = data.select_dtypes(include=['object', 'category']).columns

In [9]:
for col in numeric_columns:
    if data[col].isnull().sum() > 0:  # Check if there are missing values
        median_value = data[col].median()
        data[col] = data[col].fillna(median_value)

In [21]:
import os

In [10]:
for col in categorical_columns:
    if data[col].isnull().sum() > 0:  # Check if there are missing values
        most_frequent_value = data[col].mode()[0]
        data[col] = data[col].fillna(most_frequent_value)

In [22]:
zip_path = '/mnt/data/Bondora_raw.zip'

In [23]:
extract_path = '/mnt/data/Bondora_raw'

In [24]:
print("Files extracted to:", extract_path)

Files extracted to: /mnt/data/Bondora_raw

In [29]:
zip_path = r"C:/Users/nikhil/Downloads/Bondora_raw.zip"

In [30]:
zip_path = '/path/to/Bondora_raw.zip'
if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)

In [31]:
print(os.listdir('.'))

['.ipynb_checkpoints', '.ipython', '.jupyter', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'edb_languagepack_4.exe', 'Favorites', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{35351bc9-6b1f-11ee-a6f2-9b266bae7eab}.TM.blf', 'NTUSER.DAT{35351bc9-6b1f-11ee-a6f2-9b266bae7eab}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{35351bc9-6b1f-11ee-a6f2-9b266bae7eab}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'processed_bondora_data.csv', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Videos']

In [32]:
if os.path.exists('Bondora_raw.zip'):
    print("File is uploaded!")

In [36]:
def handle_missing_values(df):
    for column in df.columns:
        if df[column].dtype in ['float64', 'int64']:  # Numeric columns
            median_value = df[column].median()
            df[column].fillna(median_value, inplace=True)
        else:  # Categorical columns
            most_frequent = df[column].mode()[0]
            df[column].fillna(most_frequent, inplace=True)
    return df

In [11]:
# Remove duplicate rows
data_cleaned = data.drop_duplicates()

In [12]:
# Display the number of rows before and after removing duplicates
print(f"Number of rows before removing duplicates: {len(data)}")
print(f"Number of rows after removing duplicates: {len(data_cleaned)}")

Number of rows before removing duplicates: 134529
Number of rows after removing duplicates: 134529

In [24]:
# Standardize column names
data.columns = [
    '_'.join(filter(None, ''.join(e if e.isalnum() or e.isspace() else ' ' for e in col).split())).lower()
    for col in data.columns
]

In [47]:
 print(data.columns)
# Check for case inconsistencies
for col in data.columns:
    if col != col.lower():  # checks if the column name is not all lowercase
        print(f"Column name '{col}' should be standardized to lowercase.")
        # Check for columns with very long names
for col in data.columns:
    if len(col) > 50:  # for example, columns with more than 50 characters
        print(f"Column name '{col}' is too long and might need to be shortened.") 
        data.rename(columns={
    'reportasofeod': 'report_date',
    'loanid': 'loan_id',
    'loannumber': 'loan_number',
    'listedonutc': 'listed_on_utc',
    # Add more as needed
}, inplace=True)
data.columns = [col.replace('principaldebtservicingcost', 'principal_debt_serv_cost') for col in data.columns]
data.columns = [col.replace('reportasofeod','report_date') for col in data.columns]
data.columns = [col.replace('listedonutc','listed_on_utc')for col in data.columns]
data.columns = [col.replace('bidsportfoliomanager','bids_portfolio_manager') for col in data.columns]
data.columns = [col.replace('biddingstartedon','bidding_started_on') for col in data.columns]
data.columns = [col.replace('newcreditcustomer','new_credit_customer')for col in data.columns]
data.columns = [col.replace('graceperiodstart','grace_period_start')for col in data.columns]
data.columns = [col.replace('graceperiodend','grace_period_end')for col in data.columns]
data.columns = [col.replace('nextpaymentdate','next_payment_date')for col in data.columns]
data.columns = [col.replace('interestandpenaltydebtservicingcost','interest_penalty_debt_servicing_cost')for col in data.columns]
data.columns = [col.replace('activelatelastpaymentcategory','active_latelast_payment_category')for col in data.columns]
data.columns = [col.replace('nextpaymentdate','next_payment_date')for col in data.columns]
data.columns = [col.replace('nrofscheduledpayments', 'nrof_scheduled_payments')for col in data.columns]
data.columns = [col.replace('previousearlyrepaymentsbefoleloan', 'previous_early_repayments_beforeloan')for col in data.columns]
data.columns = [col.replace('previousrepaymentsbeforeloan', 'previous_repayments_beforeloan')for col in data.columns]
data.columns = [col.replace('previousearlyrepaymentscountbeforeloan', 'previous_early_repayments_count_beforeloan')for col in data.columns]
data.columns = [col.replace('amountofpreviousloansbeforeloan', 'amount_previousloans_beforeloan')for col in data.columns]

# Standardize column names by converting them to lowercase and replacing spaces with underscores
data.columns = [
    '_'.join(filter(None, ''.join(e if e.isalnum() or e.isspace() else ' ' for e in col).split())).lower()
    for col in data.columns
]
print(data.columns)

Index(['report_date', 'loanid', 'loannumber', 'listed_on_utc',
       'bidding_started_on', 'bids_portfolio_manager', 'bidsapi', 'bidsmanual',
       'username', 'new_credit_customer',
       ...
       'grace_period_start', 'grace_period_end', 'next_payment_date',
       'nextpaymentnr', 'nrof_scheduled_payments', 'rescheduledon',
       'principal_debt_serv_cost', 'interest_penalty_debt_servicing_cost',
       'active_latelast_payment_category', 'status_binary'],
      dtype='object', length=113)
Index(['report_date', 'loanid', 'loannumber', 'listed_on_utc',
       'bidding_started_on', 'bids_portfolio_manager', 'bidsapi', 'bidsmanual',
       'username', 'new_credit_customer',
       ...
       'grace_period_start', 'grace_period_end', 'next_payment_date',
       'nextpaymentnr', 'nrof_scheduled_payments', 'rescheduledon',
       'principal_debt_serv_cost', 'interest_penalty_debt_servicing_cost',
       'active_latelast_payment_category', 'status_binary'],
      dtype='object', length=113)

In [15]:
# Inspect unique values in the 'Status' column
print("Unique values in 'Status':", data['Status'].unique())

# Transform the 'Status' column into a binary variable
data['Status_Binary'] = data['Status'].apply(lambda x: 1 if x.lower() == 'late' else 0)

Unique values in 'Status': ['Repaid' 'Late' 'Current']

In [16]:
# Identify binary categorical columns (columns with only two unique values)
binary_columns = [col for col in data.columns if data[col].nunique() == 2]

# Perform label encoding for each binary column
for col in binary_columns:
    # Map the values to 0 and 1
    unique_values = data[col].unique()
    data[col] = data[col].map({unique_values[0]: 0, unique_values[1]: 1})

In [21]:
# Limit to categorical columns with a small number of unique categories
categorical_columns = [
    col for col in data.select_dtypes(include=['object', 'category']).columns
    if data[col].nunique() <= 50  # Change 50 to a suitable threshold
]

# Apply one-hot encoding to these columns only
data_encoded = pd.get_dummies(data, columns=categorical_columns, drop_first=False)

In [18]:
# Function to identify outliers using IQR
def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)  # First quartile (25th percentile)
    Q3 = df[column].quantile(0.75)  # Third quartile (75th percentile)
    IQR = Q3 - Q1                   # Interquartile range
    lower_bound = Q1 - 1.5 * IQR    # Lower bound
    upper_bound = Q3 + 1.5 * IQR    # Upper bound

    # Identify outliers
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    return outliers

# Apply the function to numeric columns
numeric_columns = data.select_dtypes(include=['number']).columns
for col in numeric_columns:
    outliers = detect_outliers_iqr(data, col)

In [20]:
 #Function to cap extreme values
def cap_extreme_values(df, column, lower_percentile=0.01, upper_percentile=0.99):
    lower_bound = df[column].quantile(lower_percentile)  # 1st percentile
    upper_bound = df[column].quantile(upper_percentile)  # 99th percentile
    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)  # Cap values

# Apply the capping function to all numeric columns
numeric_columns = data.select_dtypes(include=['number']).columns
for col in numeric_columns:
    cap_extreme_values(data, col)

In [44]:
data.head()

,report_date,loanid,loannumber,listed_on_utc,bidding_started_on,bids_portfolio_manager,bidsapi,bidsmanual,username,new_credit_customer,...,grace_period_start,grace_period_end,next_payment_date,nextpaymentnr,nrof_scheduled_payments,rescheduledon,principal_debt_serv_cost,interest_penalty_debt_servicing_cost,active_latelast_payment_category,status_binary
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,3744.96,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,0,...,2019-12-27,2020-04-27,2020-02-10,3.0,60.0,2020-01-13,0.0,0.0,180+,0
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,3744.96,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,1,...,2019-12-27,2020-04-27,2020-02-10,3.0,60.0,2020-01-13,0.0,0.0,180+,0
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,3744.96,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,0,...,2019-12-27,2020-04-27,2020-02-10,3.0,60.0,2020-01-13,0.0,0.0,180+,1
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,3744.96,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,0,...,2019-12-27,2020-04-27,2020-02-10,3.0,60.0,2020-01-13,0.0,0.0,180+,0
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,3744.96,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,0,...,2019-12-27,2020-04-27,2020-02-10,3.0,60.0,2020-01-13,0.0,0.0,180+,0

In [45]:
data.describe()

,loannumber,bids_portfolio_manager,bidsapi,bidsmanual,new_credit_customer,applicationsignedhour,applicationsignedweekday,verificationtype,languagecode,age,...,noofpreviousloansbeforeloan,amountofpreviousloansbeforeloan,previousrepaymentsbeforeloan,previousearlyrepaymentsbefoleloan,previousearlyrepaymentscountbeforeloan,nextpaymentnr,nrof_scheduled_payments,principal_debt_serv_cost,interest_penalty_debt_servicing_cost,status_binary
count,1.345290e+05,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,...,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.0,134529.000000,134529.000000
mean,9.448554e+05,950.078266,23.552795,546.284302,0.421627,13.374640,3.907908,2.817712,2.820314,40.831650,...,1.461514,2823.313415,659.370843,97.598132,0.062752,4.483494,52.872934,0.0,33.515966,0.340239
std,4.784434e+05,1267.462454,87.156894,672.332764,0.493821,4.992375,1.726192,1.407741,1.938785,12.299119,...,2.260569,4291.679944,1456.871160,549.635159,0.285329,6.016201,11.360047,0.0,138.608607,0.473791
min,3.744960e+03,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,20.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,0.0,0.000000,0.000000
25%,6.206790e+05,155.000000,0.000000,96.000000,0.000000,10.000000,2.000000,1.000000,1.000000,31.000000,...,0.000000,0.000000,54.790000,0.000000,0.000000,1.000000,48.000000,0.0,0.000000,0.000000
50%,9.235970e+05,465.000000,0.000000,317.000000,0.000000,13.000000,4.000000,4.000000,3.000000,40.000000,...,1.000000,396.354100,197.980000,0.000000,0.000000,3.000000,60.000000,0.0,0.000000,0.000000
75%,1.311025e+06,1218.000000,5.000000,729.000000,1.000000,17.000000,5.000000,4.000000,4.000000,50.000000,...,2.000000,4250.000000,415.200000,0.000000,0.000000,5.000000,60.000000,0.0,0.000000,1.000000
max,1.831649e+06,6800.000000,645.000000,3439.440000,1.000000,23.000000,7.000000,4.000000,6.000000,69.000000,...,11.000000,18992.200000,9206.956400,4250.000000,2.000000,34.000000,60.000000,0.0,976.447600,1.000000

In [48]:
data.describe()

,loannumber,bids_portfolio_manager,bidsapi,bidsmanual,new_credit_customer,applicationsignedhour,applicationsignedweekday,verificationtype,languagecode,age,...,noofpreviousloansbeforeloan,amount_previousloans_beforeloan,previous_repayments_beforeloan,previous_early_repayments_beforeloan,previous_early_repayments_count_beforeloan,nextpaymentnr,nrof_scheduled_payments,principal_debt_serv_cost,interest_penalty_debt_servicing_cost,status_binary
count,1.345290e+05,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,...,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134529.0,134529.000000,134529.000000
mean,9.448554e+05,950.078266,23.552795,546.284302,0.421627,13.374640,3.907908,2.817712,2.820314,40.831650,...,1.461514,2823.313415,659.370843,97.598132,0.062752,4.483494,52.872934,0.0,33.515966,0.340239
std,4.784434e+05,1267.462454,87.156894,672.332764,0.493821,4.992375,1.726192,1.407741,1.938785,12.299119,...,2.260569,4291.679944,1456.871160,549.635159,0.285329,6.016201,11.360047,0.0,138.608607,0.473791
min,3.744960e+03,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,20.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,0.0,0.000000,0.000000
25%,6.206790e+05,155.000000,0.000000,96.000000,0.000000,10.000000,2.000000,1.000000,1.000000,31.000000,...,0.000000,0.000000,54.790000,0.000000,0.000000,1.000000,48.000000,0.0,0.000000,0.000000
50%,9.235970e+05,465.000000,0.000000,317.000000,0.000000,13.000000,4.000000,4.000000,3.000000,40.000000,...,1.000000,396.354100,197.980000,0.000000,0.000000,3.000000,60.000000,0.0,0.000000,0.000000
75%,1.311025e+06,1218.000000,5.000000,729.000000,1.000000,17.000000,5.000000,4.000000,4.000000,50.000000,...,2.000000,4250.000000,415.200000,0.000000,0.000000,5.000000,60.000000,0.0,0.000000,1.000000
max,1.831649e+06,6800.000000,645.000000,3439.440000,1.000000,23.000000,7.000000,4.000000,6.000000,69.000000,...,11.000000,18992.200000,9206.956400,4250.000000,2.000000,34.000000,60.000000,0.0,976.447600,1.000000